version: '3.7'

services:
  # =================================================================
  # 1. INFRASTRUCTURE BLUE TEAM (WAZUH)
  # =================================================================
  wazuh.manager:
    image: wazuh/wazuh-manager:4.9.0
    hostname: wazuh.manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - ./config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
      - ./config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf
    networks:
      - net_public      # Visible pour l'admin et les agents publics
      - net_wazuh_mgmt  # Visible par les agents cachés

  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.9.0
    hostname: wazuh.indexer
    restart: always
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      - ./config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      - ./config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      - ./config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml
      - ./config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml
    networks:
      - net_wazuh_mgmt

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.9.0
    hostname: wazuh.dashboard
    restart: always
    ports:
      - 443:5601
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAZUH_API_URL=https://wazuh.manager
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=kibanaserver
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - ./config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - ./config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
      - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
    depends_on:
      - wazuh.indexer
    networks:
      - net_public
      - net_wazuh_mgmt

  # =================================================================
  # 2. RED TEAM (L'ATTAQUANT)
  # =================================================================
  kali.attacker:
    image: kalilinux/kali-rolling
    container_name: kali_attacker
    hostname: kali
    tty: true
    stdin_open: true
    networks:
      - net_public   # Kali ne voit QUE le public.

  # =================================================================
  # 3. ZONE PUBLIQUE (VISIBLE) - CIBLES FACILES
  # =================================================================
  target.ftp:
    build: ../../target-ftp
    container_name: target_ftp
    hostname: target-ftp
    networks:
      - net_public      # Visible
      - net_wazuh_mgmt  # Surveillance

  target.jenkins:
    build: ../../target-jenkins
    container_name: target_jenkins
    hostname: target-jenkins
    user: root # On lance en root pour faciliter l'attaque RCE
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false # Pas de setup wizard, accès direct
    ports:
      - "8081:8080"
    networks:
      - net_public      # Visible par Kali (Port 8080)
      - net_wazuh_mgmt  # Surveillance
  # =================================================================
  # 4. LE PIVOT (LE PONT)
  # =================================================================
  target.samba:
    build: ../../target-samba
    container_name: target_samba
    hostname: target-samba
    networks:
      - net_public        # Entrée (Visible par Kali)
      - net_intermediaire # Sortie (Visible par la DB)
      - net_wazuh_mgmt    # Surveillance

  # =================================================================
  # 5. ZONE CACHÉE (INVISIBLE DEPUIS KALI)
  # =================================================================
  target.apache:
    build: ../../target-apache
    container_name: target_apache
    hostname: target-apache
    networks:
      - net_intermediaire # CACHÉ ! (Pas de net_public)
      - net_wazuh_mgmt    # Surveillance

# =================================================================
# DÉFINITION DES RÉSEAUX
# =================================================================
networks:
  net_public:        # DMZ (Kali + FTP + Web + Samba)
    driver: bridge
  net_intermediaire: # Réseau interne (Samba + DB)
    driver: bridge
    internal: true   # Isolé d'internet
  net_wazuh_mgmt:    # Réseau de gestion (Tous + Wazuh)
    driver: bridge

# Volumes standard Wazuh
volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  filebeat_etc:
  filebeat_var:
  wazuh-indexer-data:
  wazuh-dashboard-config:
  wazuh-dashboard-custom:
